### ISSUE TITLE
JavaScript libraries issue

### ISSUE THREAD

**Issue by chanakaDe** [ampervue/ngJWPlayer#5]
Hey,

There are two jwplayer.js files. No ? I mean in your jwplayer.js, there are angular parts. And also we have to download original jwplayer js files too. So what's your jwplayer.js ???? And also there are three js files in your src folder. Imagine we are manually inserting dependencies.Not using bower. Please tell me how can we do that ???? The instructions you have given is not clear.

**Comment by dkarchmer** [comment]
The top level `jwplayer.js` or `jwplayer.min.js` (you only need one: One is the minified version of the the other one) is all you need if you want to manually add a single file to your project, but as described in the readme, I recommend using bower:

```
bower install ng-jwplayer --save
```

and then you will need to add the following lines on your HTML

```
<script type="text/javascript" src="bower_components/angular/angular.js"></script>
<!-- Remplace xxxxxxxxx with your license code given by JWPLayer -->
<script src="https://content.jwplatform.com/libraries/xxxxxxxxxxxx.js"></script>    
<script type="text/javascript" src="bower_components/ng-jwplayer/jwplayer.min.js"></script>
```

If you have used any bower libraries in the past, these instructions should be clear, as they are similar.

If you clone the depo, (instead of using bower), you can also try the `index1.html` as an example

**Comment by chanakaDe** [comment]
Yup..... I did that manually and now it's working.....
Thanks for the help bro :+1:
