### ISSUE TITLE
Even if I cose the player, video is playing background

### ISSUE THREAD

**Issue by chanakaDe** [ampervue/ngJWPlayer#6]
I have the same issue reported here.
https://support.jwplayer.com/customer/portal/questions/6062764-audio-continues-to-play-after-closing-in-ie
My player is in a bootstarp modal. Even if modal closed, its playing.
But have a problem. How can I use this code ?

jwplayer.stop();

**Comment by dkarchmer** [comment]
Did you try calling jwplayer.stop?

You should be able to do something like

```
      var player = jwplayerService.myPlayer[yourPlayerID];
      player.stop();
```

**Comment by chanakaDe** [comment]
This is the code I am using. At the end of the code, plz check I added above code. It's not working still.
https://gist.github.com/chanakaDe/3a7d9faf84bee310b3917d2a5fce6823

It gives this error.
VideoCtrl.js:132 Uncaught TypeError: Cannot read property 'stop' of undefined

Please tell me how to fix this. If you can, it's a great help.

**Comment by dkarchmer** [comment]
In https://gist.github.com/chanakaDe/3a7d9faf84bee310b3917d2a5fce6823, I don't see where you are defining `myPlayer2` which is why you are not successfully getting the player instance.

You need to pass the playerID you used on your jwplayer directive.

Once you can successfully get the player, you will be able to call `.stop()`

**Comment by dkarchmer** [comment]
No action. closing
